
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-batch-entropie-ai-v1-capturejob
  failurePolicy: Fail
  name: mcapturejob.kb.io
  rules:
  - apiGroups:
    - batch.entropie.ai
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - capturejobs
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-entropie-ai-v1-capturejob
  failurePolicy: Fail
  name: vcapturejob.kb.io
  rules:
  - apiGroups:
    - batch.entropie.ai
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - capturejobs
  sideEffects: None
