---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: entropie
  name: chaos-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaos-daemon
  template:
    metadata:
      labels:
        name: chaos-daemon
    spec:
      containers:
      - name: application
        image: entropieai/chaos-daemon
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_RAW
            - NET_ADMIN
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
